env: flex
runtime: nodejs

# [START env]
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: 0b0rg0bl0k
  SQL_DATABASE: magguru
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: magguru-net:us-central1:pg-magguru-net-backdoor
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: magguru-net:us-central1:pg-magguru-net-backdoor
# [END cloudsql_settings]
# [END app_yaml]
